In [2]:
import numpy as np

## The basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimention
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Tyoe
a.dtype

dtype('int32')

In [8]:
# Get Size
b.itemsize

8

## Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r,c]
a[1,5]

13

In [11]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [13]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [14]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [16]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D example


In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element  (work outside in)
b[0,1,1]

4

In [19]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [20]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1s matrix
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [22]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.53564124, 0.70927707],
       [0.92491178, 0.50889689],
       [0.2137581 , 0.89988961],
       [0.10213822, 0.16957677]])

In [25]:
# Random integer values
np.random.randint(5,14, size=(3,3))

array([[13,  6, 11],
       [13,  7,  7],
       [ 8, 11,  6]])

In [26]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Repeat an array
arr= np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
out = np.ones((5,5), dtype='int16')
z = np.zeros((3,3), dtype='int16')
z[1,1] = 9
out[1:-1,1:-1] = z
print(out)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Careful with copy**

In [29]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a+2

array([3, 4, 5, 6])

In [32]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [33]:
b = np.array([1,2,2,1])
a+b

array([2, 4, 5, 5])

In [34]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [35]:
a = np.ones((2,3))
print(a)

b= np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [36]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [37]:
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [38]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.min(stats)

1

In [40]:
np.max(stats)

6

In [41]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing arrays

In [42]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
# Vertically stacking vectores
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
# Horizontal stacking vectores
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneos

Load Data from file

In [48]:
# filedata = np.genfromtxt('nome do arquivo', delimiters=',')

In [53]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [64]:
a = np.arange(1,31)
b = a.reshape((6,5))
#print(b)
print(b[2:4,0:2])
#print(b[[0,1,2,3],[1,2,3,4]])
#print(b[[0,4,5],3:])

[[11 12]
 [16 17]]
